// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB9cukSUcRF0Pw9_3H2x6-tW0YfjaNqAo',
    appId: '1:956692429632:web:4be205a95c20e7d8f998a5',
    messagingSenderId: '956692429632',
    projectId: 'colcon-4pfva5',
    authDomain: 'colcon-4pfva5.firebaseapp.com',
    storageBucket: 'colcon-4pfva5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2WIxzEZ9jzMXgqDPE-mdkUb6wzhwW_8',
    appId: '1:956692429632:android:28ee34c00b6a27eaf998a5',
    messagingSenderId: '956692429632',
    projectId: 'colcon-4pfva5',
    storageBucket: 'colcon-4pfva5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgUuF5ReH6LtDBN20ChrRI0RXVWQUFFE',
    appId: '1:956692429632:ios:fa0a524c05b52054f998a5',
    messagingSenderId: '956692429632',
    projectId: 'colcon-4pfva5',
    storageBucket: 'colcon-4pfva5.firebasestorage.app',
    androidClientId: '956692429632-76e7ttvqb4giun3l8krp1gg0qc4nkfrj.apps.googleusercontent.com',
    iosClientId: '956692429632-8dacnnbm6r8mtvi7vghr1no8l8ejj3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.collabTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgUuF5ReH6LtDBN20ChrRI0RXVWQUFFE',
    appId: '1:956692429632:ios:fa0a524c05b52054f998a5',
    messagingSenderId: '956692429632',
    projectId: 'colcon-4pfva5',
    storageBucket: 'colcon-4pfva5.firebasestorage.app',
    androidClientId: '956692429632-76e7ttvqb4giun3l8krp1gg0qc4nkfrj.apps.googleusercontent.com',
    iosClientId: '956692429632-8dacnnbm6r8mtvi7vghr1no8l8ejj3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.collabTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB9cukSUcRF0Pw9_3H2x6-tW0YfjaNqAo',
    appId: '1:956692429632:web:dc6767d1de1310e0f998a5',
    messagingSenderId: '956692429632',
    projectId: 'colcon-4pfva5',
    authDomain: 'colcon-4pfva5.firebaseapp.com',
    storageBucket: 'colcon-4pfva5.firebasestorage.app',
  );
}
